version: "3.9"

services:
  api_express:
    container_name: api_express
    image: node:16
    build: .
    ports:
      - 3000:3000
    environment:
      - DB_USER=wcs
      - DB_NAME=products_management
      - DB_HOST=db
      - DB_PASSWORD=1234
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
  db:
    container_name: db
    image: postgres:14.3
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=wcs
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=products_management
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wcs -d products_management"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - postgre_entregaS417:/var/lib/postgresql/data

volumes:
  postgre_entregaS417:
    driver: local
